services:
  mc-server:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "8888:25565"
    environment:
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./minecraft:/minecraft/
    restart: unless-stopped